# Generated by Django 4.2.21 on 2025-05-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('datasource_type', models.CharField(choices=[('Postgres', 'postgres'), ('Mysql', 'Mysql'), ('Kafka', 'Kafka'), ('RabbitMQ', 'RabbitMQ'), ('S3', 'S3'), ('Hive', 'Hive'), ('HDFS', 'HDFS'), ('CSV', 'CSV')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection_params', models.JSONField()),
            ],
        ),
    ]
