# Generated by Django 4.2.21 on 2025-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
