# Generated by Django 4.2.21 on 2025-05-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0002_alter_datasource_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_schema', models.JSONField()),
                ('pre_enrichment_schema', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='usex_app.datasource')),
            ],
        ),
    ]
