# Generated by Django 4.2.21 on 2025-05-28 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0004_alter_datasourceschema_datasource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceschema',
            name='datasource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema', to='usex_app.datasource'),
        ),
    ]
