# Generated by Django 4.2.21 on 2025-05-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0005_alter_datasourceschema_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('internal_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
