# Generated by Django 4.2.21 on 2025-06-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0007_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasourceschema',
            old_name='pre_enrichment_schema',
            new_name='parsing_schema',
        ),
    ]
