# Generated by Django 4.2.21 on 2025-06-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0008_rename_pre_enrichment_schema_datasourceschema_parsing_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceschema',
            name='rejection_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
