# Generated by Django 4.2.21 on 2025-06-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0009_datasourceschema_rejection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceschema',
            name='rejection_fields',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
