# Generated by Django 4.2.21 on 2025-06-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0010_alter_datasourceschema_rejection_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceschema',
            name='enrichment_schema',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
