# Generated by Django 4.2.21 on 2025-06-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0011_datasourceschema_enrichment_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceschema',
            name='enrichment_rejection_fields',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
