# Generated by Django 4.2.21 on 2025-06-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0012_datasourceschema_enrichment_rejection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceschema',
            name='enrichment_rejection_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='datasourceschema',
            name='enrichment_schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='datasourceschema',
            name='rejection_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
