# Generated by Django 4.2.21 on 2025-06-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0013_alter_datasourceschema_enrichment_rejection_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
