# Generated by Django 4.2.21 on 2025-06-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0014_datastore_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='skip_campaign_processing',
            field=models.BooleanField(default=False, help_text='Skip campaign processing for this datasource'),
        ),
    ]
