# Generated by Django 4.2.21 on 2025-07-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0016_enums_operator_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='enum',
        ),
        migrations.RemoveField(
            model_name='templates',
            name='field',
        ),
        migrations.RemoveField(
            model_name='templates',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='templates',
            name='value',
        ),
        migrations.RemoveField(
            model_name='templates',
            name='value_type',
        ),
        migrations.AddField(
            model_name='templates',
            name='display_text',
            field=models.CharField(default='', help_text='Text to display in the UI for this condition template.', max_length=1000),
        ),
        migrations.AddField(
            model_name='templates',
            name='template_expression',
            field=models.CharField(default='', help_text='Template expression for the condition, using placeholders for fields.', max_length=1000),
        ),
    ]
