# Generated by Django 4.2.21 on 2025-07-01 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0017_remove_templates_enum_remove_templates_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='datasource',
            field=models.ForeignKey(default=None, help_text='The DataSource associated with this template.', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='usex_app.datasource'),
            preserve_default=False,
        ),
    ]
