# Generated by Django 4.2.21 on 2025-07-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0018_templates_datasource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operator',
            new_name='Operators',
        ),
    ]
