# Generated by Django 4.2.21 on 2025-07-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0019_rename_operator_operators'),
    ]

    operations = [
        migrations.AddField(
            model_name='enums',
            name='datatype',
            field=models.CharField(default='string', help_text='Data type of the enum values (e.g., string, integer).', max_length=50),
        ),
        migrations.AddField(
            model_name='enums',
            name='enum_set_id',
            field=models.CharField(blank=True, default=None, help_text='Unique ID for the enum set.', max_length=100, null=True, unique=True),
        ),
    ]
