# Generated by Django 4.2.21 on 2025-07-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0020_enums_datatype_enums_enum_set_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enums',
            name='datatype',
            field=models.CharField(default='str', help_text='Data type of the enum values (e.g., string, integer).', max_length=50),
        ),
    ]
