# Generated by Django 4.2.21 on 2025-07-03 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0022_remove_operators_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_column', models.CharField(help_text='Column from the source DataStore schema used in the relationship.', max_length=100)),
                ('target_column', models.CharField(help_text='Column from the target DataStore schema used in the relationship.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_datastore', models.ForeignKey(help_text='The source DataStore in the relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='usex_app.datastore')),
                ('target_datastore', models.ForeignKey(help_text='The target DataStore in the relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='usex_app.datastore')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'unique_together': {('source_datastore', 'target_datastore', 'source_column', 'target_column')},
            },
        ),
    ]
