# Generated by Django 4.2.21 on 2025-07-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0023_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='selection_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Schema for the selection fields in the template.', null=True),
        ),
    ]
