# Generated by Django 4.2.21 on 2025-07-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0024_templates_selection_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templates',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AlterField(
            model_name='templates',
            name='name',
            field=models.CharField(help_text='Name of the condition template.', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='templates',
            unique_together={('name', 'datasource')},
        ),
    ]
