# Generated by Django 4.2.21 on 2025-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0026_action_campaignproject_datasink_datasinkschema_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasink',
            name='sink_type',
        ),
        migrations.AddField(
            model_name='datasink',
            name='datasink_type',
            field=models.CharField(choices=[('Postgres', 'postgres'), ('Mysql', 'Mysql'), ('Kafka', 'Kafka'), ('REST API', 'REST API')], help_text='Type of the sink (e.g., Database, Kafka, API, PostRequest).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datasink',
            name='main_fields',
            field=models.JSONField(blank=True, default=list, help_text='Main fields for the sink schema.', null=True),
        ),
        migrations.AddField(
            model_name='datasink',
            name='output_schema',
            field=models.JSONField(blank=True, default=dict, help_text='Schema for the output data to be sent to the sink.', null=True),
        ),
        migrations.DeleteModel(
            name='DataSinkSchema',
        ),
    ]
