# Generated by Django 4.2.21 on 2025-07-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0027_remove_datasink_sink_type_datasink_datasink_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasink',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the sink.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='datasink',
            name='name',
            field=models.CharField(help_text='Name of the sink.', max_length=100),
        ),
    ]
