# Generated by Django 4.2.21 on 2025-07-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0028_alter_datasink_description_alter_datasink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourceschema',
            name='aggregation_schema',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
