# Generated by Django 4.2.21 on 2025-07-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0029_datasourceschema_aggregation_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', help_text='Status of the campaign.', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='version',
            field=models.CharField(default='1.0', help_text='Version of the campaign, used for tracking changes.', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('name', 'DataSource')},
        ),
    ]
