# Generated by Django 4.2.21 on 2025-07-10 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0030_campaign_status_campaign_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(blank=True, help_text='The project this campaign belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='usex_app.campaignproject'),
        ),
    ]
