# Generated by Django 4.2.21 on 2025-07-10 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0032_alter_campaign_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='datastore',
            field=models.ForeignKey(blank=True, help_text='The DataStore where campaign data will be stored.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='usex_app.datastore'),
        ),
    ]
