# Generated by Django 4.2.21 on 2025-07-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0033_campaign_datastore'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='event_filter',
            field=models.JSONField(blank=True, default=dict, help_text='Filter conditions for the campaign event, defining which events to include.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='profile_filter',
            field=models.JSONField(blank=True, default=dict, help_text='Filter conditions for the campaign profile, defining which profiles to include.', null=True),
        ),
    ]
