# Generated by Django 4.2.21 on 2025-07-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0034_campaign_event_filter_campaign_profile_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='endpoint',
            field=models.ManyToManyField(blank=True, help_text='Data sinks associated with this action.', related_name='actions', to='usex_app.datasink'),
        ),
    ]
