# Generated by Django 4.2.21 on 2025-07-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0035_action_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='enricher_params',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters for enrichment processing', null=True),
        ),
    ]
