# Generated by Django 4.2.21 on 2025-07-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0036_datasource_enricher_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='internal_name',
            field=models.CharField(blank=True, default=None, help_text='Internal name for the data source, used for Redis keys and other internal references.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(help_text='Name of the data source.', max_length=100, unique=True),
        ),
    ]
