# Generated by Django 4.2.21 on 2025-07-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0037_datasource_internal_name_alter_datasource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='internal_name',
            field=models.CharField(help_text='Internal name for the data source, used for Redis keys and other internal references.', max_length=100, unique=True),
        ),
    ]
