# Generated by Django 4.2.21 on 2025-07-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0038_alter_datasource_internal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End date and time for the campaign.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start date and time for the campaign.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('Expired', 'Expired')], default='draft', help_text='Status of the campaign.', max_length=20),
        ),
    ]
