# Generated by Django 4.2.21 on 2025-07-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0039_campaign_end_date_campaign_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='next_version',
            field=models.OneToOneField(blank=True, help_text='The next version of this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_version_campaign', to='usex_app.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='prev_version',
            field=models.OneToOneField(blank=True, help_text='The previous version of this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_version_campaign', to='usex_app.campaign'),
        ),
    ]
