# Generated by Django 4.2.21 on 2025-07-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0040_campaign_next_version_campaign_prev_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('name', 'DataSource', 'project', 'status')},
        ),
    ]
