# Generated by Django 4.2.21 on 2025-07-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0041_alter_campaign_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set(),
        ),
    ]
