# Generated by Django 4.2.21 on 2025-07-24 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0042_alter_action_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the action template.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the action template.')),
                ('display_text', models.CharField(default='', help_text='Text to display in the UI for this action template.', max_length=1000)),
                ('template_expression', models.CharField(default='', help_text='Template expression for the action, using placeholders for fields.', max_length=1000)),
                ('selection_schema', models.JSONField(blank=True, default=dict, help_text='Schema for the selection fields in the action template.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasource', models.ForeignKey(help_text='The DataSource associated with this action template.', on_delete=django.db.models.deletion.CASCADE, related_name='action_templates', to='usex_app.datasource')),
            ],
            options={
                'verbose_name': 'Action Template',
                'verbose_name_plural': 'Action Templates',
                'unique_together': {('name', 'datasource')},
            },
        ),
    ]
