# Generated by Django 4.2.21 on 2025-07-31 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0043_actiontemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemainderAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(help_text='Unique identifier for the action.', max_length=50)),
                ('profile_attributes', models.JSONField(blank=True, default=dict, help_text='Attributes for the profile associated with this action.', null=True)),
                ('feed_attributes', models.JSONField(blank=True, default=dict, help_text='Attributes for the event associated with this action.', null=True)),
                ('reminder_time', models.IntegerField(default=0, help_text='Time in seconds after which the action should be triggered as a reminder.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ManyToManyField(blank=True, help_text='Data sinks associated with this action.', related_name='remainder_actions', to='usex_app.datasink')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='MilestoneAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(help_text='Unique identifier for the action.', max_length=50)),
                ('profile_attributes', models.JSONField(blank=True, default=dict, help_text='Attributes for the profile associated with this action.', null=True)),
                ('feed_attributes', models.JSONField(blank=True, default=dict, help_text='Attributes for the event associated with this action.', null=True)),
                ('milestone_value', models.JSONField(blank=True, default=dict, help_text='Attributes for the profile associated with this action.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ManyToManyField(blank=True, help_text='Data sinks associated with this action.', related_name='milestone_actions', to='usex_app.datasink')),
            ],
            options={
                'verbose_name': 'MilestoneAction',
                'verbose_name_plural': 'MilestoneActions',
            },
        ),
        migrations.CreateModel(
            name='EventAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(help_text='Unique identifier for the action.', max_length=50)),
                ('template_expression', models.CharField(default='', help_text='Template expression for the condition, using placeholders for fields.', max_length=1000)),
                ('time_limit', models.IntegerField(default=0, help_text='Time limit for the action in seconds. If 0, no time limit is applied.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fulfillment_action', models.ForeignKey(help_text='The action to be fulfilled when this event action is triggered.', on_delete=django.db.models.deletion.CASCADE, related_name='event_actions', to='usex_app.action')),
                ('milestone_actions', models.ManyToManyField(blank=True, help_text='Milestone actions to be taken when this event action is triggered.', related_name='milestone_event_actions', to='usex_app.milestoneaction')),
                ('remainder_actions', models.ManyToManyField(blank=True, help_text='Actions to be taken as a remainder when this event action is triggered.', related_name='remainder_event_actions', to='usex_app.remainderaction')),
            ],
        ),
    ]
