# Generated by Django 4.2.21 on 2025-07-31 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usex_app', '0044_remainderaction_milestoneaction_eventaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remainderaction',
            old_name='reminder_time',
            new_name='reminder_timeinterval',
        ),
    ]
