"""
Django settings for my_django_project.

Generated by 'django-admin startproject' using Django 4.x.

For more information on this file, see
https://docs.djangoproject.com/en/4.x/topics/settings/

"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.x/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'your-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usex_app',
    'corsheaders',
    # Add your apps here
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_django_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_django_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.x/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'usex_app',
        'USER': 'django_user',
        'PASSWORD': 'Asg@a$rd1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.x/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.x/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Singapore'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.x/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.x/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:8000",  # Add your frontend's URL here
    "http://localhost:8000",
]
from decouple import config

# Datastore Redis Configuration
DATASTORE_REDIS_HOST = config('DATASTORE_REDIS_HOST', default='localhost')
DATASTORE_REDIS_PORT = config('DATASTORE_REDIS_PORT', cast=int, default=6379)
DATASTORE_REDIS_DB = config('DATASTORE_REDIS_DB', cast=int, default=0)
DATASTORE_REDIS_PASSWORD = config('DATASTORE_REDIS_PASSWORD', default='')

# Aggregate Redis Configuration
AGGREGATE_REDIS_HOST = config('AGGREGATE_REDIS_HOST', default='localhost')
AGGREGATE_REDIS_PORT = config('AGGREGATE_REDIS_PORT', cast=int, default=6380)
AGGREGATE_REDIS_DB = config('AGGREGATE_REDIS_DB', cast=int, default=1)
AGGREGATE_REDIS_PASSWORD = config('AGGREGATE_REDIS_PASSWORD', default='')

# Kafka Configuration
KAFKA_BROKER_URL = config('KAFKA_BROKER_URL', default='localhost:9092')
KAFKA_SCHEMA_REGISTRY_URL = config('KAFKA_SCHEMA_REGISTRY_URL', default='http://localhost:8081')
KAFKA_CONSUMER_GROUP = config('KAFKA_CONSUMER_GROUP', default='my_consumer_group')
KAFKA_TOPIC = config('KAFKA_TOPIC', default='my_topic')